CREATE DATABASE Characters;
USE Characters;
CREATE TABLE char_table(char_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,name VARCHAR(20) NOT NULL,char_class VARCHAR(20) NOT NULL,level INT NOT NULL,experience INT NOT NULL,attack INT NOT NULL,defense INT NOT NULL,hit INT NOT NULL,Weapon BOOLEAN,Armor BOOLEAN,Helm BOOLEAN);
